import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ImageContainer, Logo, SingleStoreCard } from "../components/elements";
import { signIn, signOut } from "next-auth/react";
import prisma from "../utils/prismadb.js";

export default function Home({ stores }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=" body-font font-bold">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:flex-grow order-2 md:order-1 md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <Logo />
              <div className="font-extrabold text-4xl mb-8 mt-4">
                <h1 className="text-primary ">Maduka shops</h1>
                <h1 className=" ">Premuium ecommerce</h1>
              </div>
              <h3 className="title-font sm:text-xl text-xl mb-4 font-bold text-gray-900">
                Our online store is specially designed to meet the needs for a
                small businesses
              </h3>
              <p className="mb-8 leading-relaxed text-gray-500">
                Maduka is aimed at helping small businesses to have an online
                presence and sell their products online. The free package helps
                you setup your store at no cost and start selling your products
                online. The premium package helps you to have a more
                professional store and also helps you to sell your products on
                other platforms like facebook, instagram, whatsapp and many
                more.
              </p>
              <Link href={"/new/store"}>
                <button className="inline-flex text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-primary/80 rounded text-lg">
                  Get Started
                </button>
              </Link>
              <button
                onClick={() => signIn()}
                className="inline-flex text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-primary/80 rounded text-lg"
              >
                sign in
              </button>
              <button
                onClick={() => signOut()}
                className="inline-flex text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-primary/80 rounded text-lg"
              >
                sign out
              </button>
            </div>
            <div className="lg:max-w-lg hidden md:block lg:w-full md:w-1/2 w-5/6 order-1 md:order-2 ">
              <ImageContainer alt="shopping icon" src={"./hero.svg"} />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="container mx-auto px-4">
            <h1 className="font-bold text-3xl mb-4">Featured Stores</h1>
            <ul>
              {stores.length > 0 &&
                stores.map((store) => (
                  <SingleStoreCard store={store} key={store.id} />
                ))}
            </ul>
          </div>
        </section>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const stores = await prisma.store.findMany({});

  return {
    props: {
      stores: JSON.parse(JSON.stringify(stores)),
    },
  };
}
